import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Sidebar } from '@/components/Sidebar'
import enData from '../../../messages/en.json'
import ptData from '../../../messages/pt.json'
import { ThemeProvider } from 'next-themes'
import { NextIntlClientProvider, useMessages } from 'next-intl'
// @ts-expect-error modulo criado pelo user
import { selecionarArquivo } from 'module-translations'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: string }
}) {
  const messages = useMessages()

  if (locale === 'pt') {
    selecionarArquivo(ptData)
  } else {
    selecionarArquivo(enData)
  }

  return (
    <html lang={locale} className="antialiased">
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider attribute="class" enableSystem>
            <div className="min-h-screen dark:bg-zinc-900 lg:grid lg:grid-cols-app">
              <Sidebar />
              <main className="max-w-[100vw] px-4 pb-12 pt-24 lg:col-start-2 lg:px-8 lg:pt-8">
                {children}
              </main>
            </div>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
